### ISSUE TITLE
import file does not work even for Z files

### ISSUE THREAD

**Issue by SummiaShah** [Z-Editor/Z-Editor#28] opened 2019-05-03 21:05 UTC
### Prerequisites

* [x] Are you running the latest version?
* [ ] Did you check this issue in Issue section?
* [ ] Did you check the debugging guide?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please add the browser details with its version.

**Comment by nadunindunil** [comment] 2019-05-04 08:13
@SummiaShah Did you export this specific Z file from our Z-editor. If not it won't work. Z-editor can parse only .z files exported from Z-editor application only.

**Comment by jamesshaw99** [comment] 2019-05-20 11:32
i made a file in z-editor and then downloaded it, when i try to import it nothing happens

**Comment by nadunindunil** [comment] 2019-05-20 12:15
Hi @jamesshaw99 , 
I couldn't reproduce the issue could you please send me the downloaded file. so we can reproduce this.
You can also check the file by opening it using a code editor. It should be a JSON file.

**Comment by jamesshaw99** [comment] 2019-05-20 13:08
[z-editor.zip](https://github.com/Z-Editor/Z-Editor/files/3198026/z-editor.zip)

**Comment by nadunindunil** [comment] 2019-05-20 13:31
Hi @jamesshaw99,
I went through the file and found that some characters are not generated from Z-editor (maybe you added them by copy paste or keyboard shortcuts).
I did a clean for your file and it still has few unrecognizable chars.
you can add those chars by import this file and add chars **using Z-editor** tools.

hope this will help you.
[new.ze.zip](https://github.com/Z-Editor/Z-Editor/files/3198126/new.ze.zip)

**Comment by sushilldhakal** [comment] 2019-05-29 03:54
same issue with me too. Haven added any other words beside from z editor @nadunindunil 
It was working when I was using z editor for a small number of Z schema but when I when it went by 2-3 pages then Import just stop working. Can you have a look, about this issue. 

Also, thank you and all your team for making it an online app, really appreciated.  
[assignment2.ze.zip](https://github.com/Z-Editor/Z-Editor/files/3230686/assignment2.ze.zip)

**Comment by nadunindunil** [comment] 2019-05-29 05:59
Hi @sushilldhakal,
Thank you very much for your feedbacks It seems something went wrong in Unicode characters into UTF-8 conversion. We are working full steam ahead to fix this issue and I will let you know as soon as possible we make progress.

**Comment by nadunindunil** [comment] 2019-06-23 16:37
Hi @SummiaShah , @jamesshaw99 ,
We have found the issue with download option and fixed it. Please let us know if you face any inconveniences.
Thank you.

**Comment by nadunindunil** [comment] 2019-06-27 13:51
Closing this issue after the release of the newest version.

**Closed by nadunindunil** 2019-06-27 13:51 UTC
Labels: bug, help wanted
